# COVID-19 Vaccination Analysis — India

## 1. Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 2. Load Dataset

In [3]:
df = pd.read_csv("covid_vaccine_statewise.csv")

## 3. Dataset Overview

### 3.1 View First 5 Rows

In [4]:
df.head(5)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

### 3.2 View Last 5 Rows

In [5]:
df.tail(5)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 3.3 Number of Rows and Columns

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 7845
Columns: 24

In [ ]:
list(df.columns)

### 3.5 Data Types of Each Column

In [7]:
df.dtypes

Updated On                              object
State                                   object
Total Doses Administered               float64
Sessions                               float64
 Sites                                 float64
First Dose Administered                float64
Second Dose Administered               float64
Male (Doses Administered)              float64
Female (Doses Administered)            float64
Transgender (Doses Administered)       float64
 Covaxin (Doses Administered)          float64
CoviShield (Doses Administered)        float64
Sputnik V (Doses Administered)         float64
AEFI                                   float64
18-44 Years (Doses Administered)       float64
45-60 Years (Doses Administered)       float64
60+ Years (Doses Administered)         float64
18-44 Years(Individuals Vaccinated)    float64
45-60 Years(Individuals Vaccinated)    float64
60+ Years(Individuals Vaccinated)      float64
Male(Individuals Vaccinated)           float64
Female(Individuals Vaccinated)         float64
Transgender(Individuals Vaccinated)    float64
Total Individuals Vaccinated           float64
dtype: object

### 3.6 Statistical Summary

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Total Doses Administered,7621.0,9.188171e+06,3.746180e+07,7.0,135657.00,818202.0,6625243.00,513228400.0
Sessions,7621.0,4.792358e+05,1.911511e+06,0.0,6004.00,45470.0,342869.00,35010311.0
Sites,7621.0,2.282872e+03,7.275974e+03,0.0,69.00,597.0,1708.00,73933.0
First Dose Administered,7621.0,7.414415e+06,2.995209e+07,7.0,116632.00,661459.0,5387805.00,400150406.0
Second Dose Administered,7621.0,1.773755e+06,7.570382e+06,0.0,12831.00,138818.0,1166434.00,113077994.0
Male (Doses Administered),7461.0,3.620156e+06,1.737938e+07,0.0,56555.00,389785.0,2735777.00,270163622.0
Female (Doses Administered),7461.0,3.168416e+06,1.515310e+07,2.0,52107.00,334238.0,2561513.00,239518609.0
Transgender (Doses Administered),7461.0,1.162978e+03,5.931354e+03,0.0,8.00,113.0,800.00,98275.0
Covaxin (Doses Administered),7621.0,1.044669e+06,4.452259e+06,0.0,0.00,11851.0,757930.00,62367416.0
CoviShield (Doses Administered),7621.0,8.126553e+06,3.298414e+07,7.0,133134.00,756736.0,6007817.00,446825051.0
Sputnik V (Doses Administered),2995.0,9.655571e+03,4.388254e+04,0.0,0.00,0.0,2519.00,588039.0
AEFI,5438.0,1.139403e+03,3.454608e+03,0.0,109.25,294.0,808.00,26542.0
18-44 Years (Doses Administered),1702.0,8.773958e+06,2.660829e+07,26624.0,434484.25,3095970.0,7366240.75,224330364.0
45-60 Years (Doses Administered),1702.0,7.442161e+06,2.225999e+07,16815.0,232627.50,2695938.0,6969726.50,166757453.0
60+ Years (Doses Administered),1702.0,5.641605e+06,1.681650e+07,9994.0,128560.50,1805696.5,5294762.75,118692689.0
18-44 Years(Individuals Vaccinated),3733.0,1.395895e+06,5.501454e+06,1059.0,56554.00,294727.0,910516.00,92243148.0
45-60 Years(Individuals Vaccinated),3734.0,2.916515e+06,9.567607e+06,1136.0,92482.25,833039.5,2499280.50,90968877.0
60+ Years(Individuals Vaccinated),3734.0,2.627444e+06,8.192225e+06,558.0,56159.75,788742.5,2337874.00,67310981.0
Male(Individuals Vaccinated),160.0,4.461687e+07,3.950749e+07,23757.0,5739350.00,37165905.0,74416634.50,134941971.0
Female(Individuals Vaccinated),160.0,3.951018e+07,3.417684e+07,24517.0,5023407.25,33654024.5,66853682.25,115668447.0
Transgender(Individuals Vaccinated),160.0,1.237054e+04,1.248503e+04,2.0,1278.75,8007.5,19851.00,46462.0
Total Individuals Vaccinated,5919.0,4.547842e+06,1.834182e+07,7.0,74275.50,402288.0,3501562.00,250656880.0

### 3.7 Dataset Info

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7845 entries, 0 to 7844
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           7845 non-null   object
 1   State                                7845 non-null   object
 2   Total Doses Administered             7621 non-null   float64
 3   Sessions                             7621 non-null   float64
 4    Sites                               7621 non-null   float64
 5   First Dose Administered              7621 non-null   float64
 6   Second Dose Administered             7621 non-null   float64
 7   Male (Doses Administered)            7461 non-null   float64
 8   Female (Doses Administered)          7461 non-null   float64
 9   Transgender (Doses Administered)     7461 non-null   float64
 10   Covaxin (Doses Administered)        7621 non-null   float64
 11  CoviShield (Doses Administered)      7621 non-null   float64
 12  Sputnik V (Doses Administered)       2995 non-null   float64
 13  AEFI                                 5438 non-null   float64
 14  18-44 Years (Doses Administered)     1702 non-null   float64
 15  45-60 Years (Doses Administered)     1702 non-null   float64
 16  60+ Years (Doses Administered)       1702 non-null   float64
 17  18-44 Years(Individuals Vaccinated)  3733 non-null   float64
 18  45-60 Years(Individuals Vaccinated)  3734 non-null   float64
 19  60+ Years(Individuals Vaccinated)    3734 non-null   float64
 20  Male(Individuals Vaccinated)         160 non-null    float64
 21  Female(Individuals Vaccinated)       160 non-null    float64
 22  Transgender(Individuals Vaccinated)  160 non-null    float64
 23  Total Individuals Vaccinated         5919 non-null   float64
dtypes: float64(22), object(2)
memory usage: 1.4+ MB

### 3.8 Count of Missing Values Per Column

In [10]:
df.isnull().sum().sort_values(ascending=False)

Transgender(Individuals Vaccinated)    7685
Female(Individuals Vaccinated)         7685
Male(Individuals Vaccinated)           7685
60+ Years (Doses Administered)         6143
45-60 Years (Doses Administered)       6143
18-44 Years (Doses Administered)       6143
Sputnik V (Doses Administered)         4850
18-44 Years(Individuals Vaccinated)    4112
60+ Years(Individuals Vaccinated)      4111
45-60 Years(Individuals Vaccinated)    4111
AEFI                                   2407
Total Individuals Vaccinated           1926
Transgender (Doses Administered)        384
Female (Doses Administered)             384
Male (Doses Administered)               384
CoviShield (Doses Administered)         224
 Covaxin (Doses Administered)           224
Second Dose Administered                224
First Dose Administered                 224
 Sites                                  224
Sessions                                224
Total Doses Administered                224
State                                     0
Updated On                                0
dtype: int64

### 3.9 Percentage of Missing Values

In [11]:
missing_pct = (df.isnull().sum() / len(df)) * 100
missing_pct[missing_pct > 0].sort_values(ascending=False)

Transgender(Individuals Vaccinated)    97.960484
Female(Individuals Vaccinated)         97.960484
Male(Individuals Vaccinated)           97.960484
18-44 Years (Doses Administered)       78.304653
60+ Years (Doses Administered)         78.304653
45-60 Years (Doses Administered)       78.304653
Sputnik V (Doses Administered)         61.822817
18-44 Years(Individuals Vaccinated)    52.415551
60+ Years(Individuals Vaccinated)      52.402804
45-60 Years(Individuals Vaccinated)    52.402804
AEFI                                   30.681963
Total Individuals Vaccinated           24.550669
Transgender (Doses Administered)        4.894837
Female (Doses Administered)             4.894837
Male (Doses Administered)               4.894837
Sessions                                2.855322
CoviShield (Doses Administered)         2.855322
 Covaxin (Doses Administered)           2.855322
Second Dose Administered                2.855322
First Dose Administered                 2.855322
 Sites                                  2.855322
Total Doses Administered                2.855322
dtype: float64

## 4. Handling Missing Values

### 4.1 Fill First Dose with Column Mean

In [12]:
mean_first = df["First Dose Administered"].mean()
df["First Dose Administered"].fillna(mean_first, inplace=True)
print("Mean used for First Dose:", round(mean_first, 2))

Mean used for First Dose: 7414415.3

C:\Users\Prathmesh\AppData\Local\Temp\ipykernel_16972\3565208910.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["First Dose Administered"].fillna(mean_first, inplace=True)

### 4.2 Fill Second Dose with Column Mean

In [13]:
mean_second = df["Second Dose Administered"].mean()
df["Second Dose Administered"].fillna(mean_second, inplace=True)
print("Mean used for Second Dose:", round(mean_second, 2))

Mean used for Second Dose: 1773755.24

C:\Users\Prathmesh\AppData\Local\Temp\ipykernel_16972\2325852131.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Second Dose Administered"].fillna(mean_second, inplace=True)

### 4.3 Confirm No Missing Values Remain in Dose Columns

In [14]:
print(df[["First Dose Administered", "Second Dose Administered"]].isnull().sum())

First Dose Administered     0
Second Dose Administered    0
dtype: int64

## 5. Data Analysis

### 5.1 State-wise Total First Dose Count

In [15]:
first_dose_state = df.groupby('State')['First Dose Administered'].sum().reset_index()
first_dose_state.columns = ['State', 'Total First Dose']
first_dose_state.sort_values('Total First Dose', ascending=False)

                                       State  Total First Dose
13                                     India      2.830663e+10
34                             Uttar Pradesh      2.832898e+09
21                               Maharashtra      2.828851e+09
29                                 Rajasthan      2.245531e+09
10                                   Gujarat      2.176133e+09
16                                 Karnataka      1.917816e+09
20                            Madhya Pradesh      1.841091e+09
36                               West Bengal      1.840936e+09
4                                      Bihar      1.514989e+09
31                                Tamil Nadu      1.333019e+09
1                             Andhra Pradesh      1.277347e+09
17                                    Kerala      1.238332e+09
26                                    Odisha      1.077120e+09
32                                 Telangana      9.248071e+08
6                               Chhattisgarh      8.404894e+08
11                                   Haryana      8.002848e+08
8                                      Delhi      6.762404e+08
15                                 Jharkhand      6.481602e+08
3                                      Assam      6.300867e+08
28                                    Punjab      6.288331e+08
14                         Jammu and Kashmir      4.545883e+08
35                               Uttarakhand      4.076779e+08
12                          Himachal Pradesh      3.607805e+08
33                                   Tripura      2.371762e+08
9                                        Goa      1.204779e+08
22                                   Manipur      1.118961e+08
23                                 Meghalaya      1.071025e+08
2                          Arunachal Pradesh      9.349147e+07
24                                   Mizoram      9.235957e+07
5                                 Chandigarh      8.918960e+07
25                                  Nagaland      8.689726e+07
27                                Puducherry      8.583335e+07
7   Dadra and Nagar Haveli and Daman and Diu      8.549597e+07
30                                    Sikkim      8.146742e+07
18                                    Ladakh      6.229574e+07
0                Andaman and Nicobar Islands      6.091235e+07
19                               Lakshadweep      4.885015e+07

### 5.2 State-wise Total Second Dose Count

In [16]:
second_dose_state = df.groupby('State')['Second Dose Administered'].sum().reset_index()
second_dose_state.columns = ['State', 'Total Second Dose']
second_dose_state.sort_values('Total Second Dose', ascending=False)

                                       State  Total Second Dose
13                                     India       6.770264e+09
21                               Maharashtra       7.235236e+08
10                                   Gujarat       6.110609e+08
36                               West Bengal       5.967894e+08
34                             Uttar Pradesh       5.650776e+08
29                                 Rajasthan       5.023455e+08
16                                 Karnataka       4.378297e+08
17                                    Kerala       3.746913e+08
1                             Andhra Pradesh       3.694601e+08
20                            Madhya Pradesh       3.275755e+08
31                                Tamil Nadu       3.013132e+08
4                                      Bihar       2.814331e+08
26                                    Odisha       2.619453e+08
32                                 Telangana       2.087955e+08
8                                      Delhi       2.006352e+08
6                               Chhattisgarh       1.827629e+08
11                                   Haryana       1.692986e+08
3                                      Assam       1.414313e+08
15                                 Jharkhand       1.327636e+08
28                                    Punjab       1.317635e+08
35                               Uttarakhand       1.107276e+08
14                         Jammu and Kashmir       9.659418e+07
12                          Himachal Pradesh       8.448111e+07
33                                   Tripura       7.591267e+07
9                                        Goa       2.684071e+07
23                                 Meghalaya       2.280916e+07
2                          Arunachal Pradesh       2.257485e+07
22                                   Manipur       2.250068e+07
5                                 Chandigarh       2.223627e+07
24                                   Mizoram       2.064095e+07
30                                    Sikkim       2.036617e+07
25                                  Nagaland       1.984717e+07
27                                Puducherry       1.925139e+07
7   Dadra and Nagar Haveli and Daman and Diu       1.701070e+07
18                                    Ladakh       1.609629e+07
0                Andaman and Nicobar Islands       1.476109e+07
19                               Lakshadweep       1.169898e+07

### 5.3 Total Male Individuals Vaccinated

In [17]:
total_male = int(df["Male(Individuals Vaccinated)"].sum())
print(f"Total Male Vaccinated: {total_male:,}")

Total Male Vaccinated: 7,138,698,858

### 5.4 Total Female Individuals Vaccinated

In [18]:
total_female = int(df["Female(Individuals Vaccinated)"].sum())
print(f"Total Female Vaccinated: {total_female:,}")

Total Female Vaccinated: 6,321,628,736

### 5.5 Gender-wise Vaccination Comparison